apiVersion: v1
kind: Service
metadata:
  name: mavenapp-service
spec:
  selector:
    app: mavenapp
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8080   
  type: NodePort 
  
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /readiness
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10

